name: Main.js CI


on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
  
    # - run: npm install 
    # - run: npm install express-rate-limit
  # comment
    

    - name: 'Create env file'
      run: |
          echo whoami
          # cp -R /var/www/dataseed-node-modules/node_modules /var/www/sandbox.egoras.com/actions-runner/_work/EgoPay-Staging/EgoPay-Staging/
          # cp -R /var/www/dataseed-node-modules/node_modules /var/www/saltlake.egoras.com/actions-runner/_work/Salt-Lake-Backend/Salt-Lake-Backend/
          npm install
          touch .env
          echo DB_HOST=${{secrets.DB_HOST}} >> .env
          echo DB_USER=${{secrets.DB_USER}} >> .env
          echo DB_PASS=${{secrets.DB_PASS}} >> .env
          echo DB_NAME=${{secrets.DB_NAME}} >> .env
          echo DB_DIALECT=${{secrets.DB_DIALECT}} >> .env
          echo DB_PORT=${{secrets.DB_PORT}} >> .env
          echo APP_HOST=${{secrets.APP_HOST}} >> .env
          echo PORT=${{secrets.PORT}} >> .env
          echo IS_GOOGLE_AUTH_ENABLE=${{secrets.IS_GOOGLE_AUTH_ENABLE}} >> .env
          echo TERMII_API_KEY=${{secrets.TERMII_API_KEY}} >> .env
          echo TERMII_SEC_KEY=${{secrets.TERMII_SEC_KEY}} >> .env
          echo SALTROUNDS=${{secrets.SALTROUNDS}} >> .env
          echo SECRET=${{secrets.SECRET}} >> .env
          echo WEB3_PROVIDER=${{secrets.WEB3_PROVIDER}} >> .env
          echo WATU_PUBLIC_KEY=${{secrets.WATU_PUBLIC_KEY}} >> .env
          echo WATU_SECRET_KEY=${{secrets.WATU_SECRET_KEY}} >> .env
          echo WATU_ENCRYPTION_KEY=${{secrets.WATU_ENCRYPTION_KEY}} >> .env
          echo WATU_IV_KEY=${{secrets.WATU_IV_KEY}} >> .env
          echo PRIVIDUS_BANK_ID=${{secrets.PRIVIDUS_BANK_ID}} >> .env
          echo WATU_BASE_URL=${{secrets.WATU_BASE_URL}} >> .env
          echo WATU_PIN=${{secrets.WATU_PIN}} >> .env
          echo WATU_DEPOSIT_PUBLIC_KEY=${{secrets.WATU_DEPOSIT_PUBLIC_KEY}} >> .env
          echo WATU_DEPOSIT_SECRET_KEY=${{secrets.WATU_DEPOSIT_SECRET_KEY}} >> .env
          echo WATU_DEPOSIT_ENCRYPTION_KEY=${{secrets.WATU_DEPOSIT_ENCRYPTION_KEY}} >> .env
          echo WATU_DEPOSIT_IV_KEY=${{secrets.WATU_DEPOSIT_IV_KEY}} >> .env
          echo YOU_VERIFY_API_KEY=${{secrets.YOU_VERIFY_API_KEY}} >> .env
          echo YOU_VERIFY_LIVE_API_KEY=${{secrets.YOU_VERIFY_LIVE_API_KEY}} >> .env
          echo YOU_VERIFY_MAINNET_ENDPOINT=${{secrets.YOU_VERIFY_MAINNET_ENDPOINT}} >> .env
          echo YOU_VERIFY_TESTNET_ENDPOINT=${{secrets.YOU_VERIFY_TESTNET_ENDPOINT}} >> .env
          echo KORA_PBK_LIVE_KEY=${{secrets.KORA_PBK_LIVE_KEY}} >> .env
          echo PVCT=${{secrets.PVCT}} >> .env

          
    - name: 'Restart server'
      run: |
          pm2 restart 11
         
         

         
          
